---
title: "week3_exercise"
author: "Aiyana Signer"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readr") 
library(ggplot2)
library(tidyverse)
library("sf") 
```

## Prepare Data
```{r}
# import data
posmo <- read_delim("data/posmo_2023-01-01T00_00_00+01_00-2023-05-01T23_59_59+02_00.csv", ",")

# Keep only the necessary columns
posmo <- select(posmo, datetime, lon_x, lat_y)

posmo <- st_as_sf(posmo, coords = c("lon_x","lat_y"), crs = 4326, remove = FALSE, na.fail = FALSE) |>
  st_transform(2056)

head(posmo)
```

```{r}
# coordinates in separate columns
posmo_coordinates <- st_coordinates(posmo)

posmo <- cbind(posmo, posmo_coordinates)
```

```{r}
posmo_filter <- posmo |>
    filter(as.Date(datetime) == "2023-04-14")
```

## Task 1: Segmentation
```{r}
#b. Measure the distance from every point to every other point
posmo_filter <- posmo_filter |>
  mutate(
    nPlus1 = sqrt((lead(X,1)-X)^2 + (lead(Y,1)-Y)^2),
    nPlus2 = sqrt((lead(X,2)-X)^2 + (lead(Y,2)-Y)^2),
    nMinus1 = sqrt((lag(X,1)-X)^2 + (lag(Y,1)-Y)^2),
    nMinus2 = sqrt((lag(X,2)-X)^2 + (lag(Y,2)-Y)^2)
    )

# row-wise step mean
posmo_filter <- posmo_filter |> 
  rowwise() |> 
  mutate( stepMean = mean(c(nMinus2, nMinus1, nPlus1, nPlus2)) 
          ) |> 
  ungroup()

#c. Remove “static points”
# These are points where the average distance is less than a given threshold. This segments the trajectory into subtrajectories
posmo_filter <- posmo_filter |> 
  ungroup() |> 
  mutate(static = stepMean < mean(stepMean, na.rm = TRUE))

posmo_filter_stat <- posmo_filter |>
  filter(!static)

posmo_filter_stat |> 
  ggplot(aes(X, Y)) + 
  geom_path() + 
  geom_point() + 
  coord_fixed() + 
  theme(legend.position = "bottom")
```

## Task 2: Specify and apply threshold d

## Task 3: Visualize segmented trajectories

## Task 4: Segment-based analysis

## Task 5: Similarity measures

## Task 6: Caluclate similarity